//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
// <copyright file="ModuleMap.cs">
//		Copyright(c)2013 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：QuickRMS.Domain.Data
//		生成时间：2014-07-02 14:33
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

using Quick.Framework.EFData;
using QuickRMS.Domain.Models.Authen;


namespace QuickRMS.Domain.Data.Mapping.Authen
{
    /// <summary>
    /// 数据表映射 —— Module
    /// </summary>    
	partial class ModuleMap
    {
        /// <summary>
		/// 映射配置
		/// </summary>
        partial void ModuleMapAppend()
        {
			// Primary Key
            this.HasKey(t => t.Id);

            // Properties
             
                            this.Property(t => t.Name).HasMaxLength(100);;
                         
                            this.Property(t => t.LinkUrl).HasMaxLength(100);;
                         
                            this.Property(t => t.Area).HasMaxLength(100);;
                         
                            this.Property(t => t.Controller).HasMaxLength(100);;
                         
                            this.Property(t => t.Action).HasMaxLength(100);;
                         
                            this.Property(t => t.Icon).HasMaxLength(100);;
                         
                            this.Property(t => t.Code).HasMaxLength(100);;
                         
                            this.Property(t => t.OrderSort);
                         
                            this.Property(t => t.Description).HasMaxLength(100);;
                         
                            this.Property(t => t.IsMenu);
                         
                            this.Property(t => t.Enabled);
                         
                            this.Property(t => t.CreateId);
                         
                            this.Property(t => t.CreateBy).HasMaxLength(100);;
                         
                            this.Property(t => t.CreateTime);
                         
                            this.Property(t => t.ModifyId);
                         
                            this.Property(t => t.ModifyBy).HasMaxLength(100);;
                         
                            this.Property(t => t.ModifyTime);
                         
                            this.Property(t => t.IsDeleted);
                                    

            // Table & Column Mappings
            this.ToTable("Common_Authen_Module");
            this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
             
                this.Property(t => t.ParentId).HasColumnName("ParentId");
             
                this.Property(t => t.Name).HasColumnName("Name");
             
                this.Property(t => t.LinkUrl).HasColumnName("LinkUrl");
             
                this.Property(t => t.Area).HasColumnName("Area");
             
                this.Property(t => t.Controller).HasColumnName("Controller");
             
                this.Property(t => t.Action).HasColumnName("Action");
             
                this.Property(t => t.Icon).HasColumnName("Icon");
             
                this.Property(t => t.Code).HasColumnName("Code");
             
                this.Property(t => t.OrderSort).HasColumnName("OrderSort");
             
                this.Property(t => t.Description).HasColumnName("Description");
             
                this.Property(t => t.IsMenu).HasColumnName("IsMenu");
             
                this.Property(t => t.Enabled).HasColumnName("Enabled");
             
                this.Property(t => t.CreateId).HasColumnName("CreateId");
             
                this.Property(t => t.CreateBy).HasColumnName("CreateBy");
             
                this.Property(t => t.CreateTime).HasColumnName("CreateTime");
             
                this.Property(t => t.ModifyId).HasColumnName("ModifyId");
             
                this.Property(t => t.ModifyBy).HasColumnName("ModifyBy");
             
                this.Property(t => t.ModifyTime).HasColumnName("ModifyTime");
             
                this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              
            // Relation
              
             this.HasOptional(t => t.ParentModule).WithMany(t => t.ChildModule).HasForeignKey(d => d.ParentId);
              
        }

		
    }
}
