//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
// <copyright file="UserRoleMap.cs">
//		Copyright(c)2013 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：QuickRMS.Domain.Data
//		生成时间：2014-07-02 14:33
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

using Quick.Framework.EFData;
using QuickRMS.Domain.Models.Authen;


namespace QuickRMS.Domain.Data.Mapping.Authen
{
    /// <summary>
    /// 数据表映射 —— UserRole
    /// </summary>    
	partial class UserRoleMap
    {
        /// <summary>
		/// 映射配置
		/// </summary>
        partial void UserRoleMapAppend()
        {
			// Primary Key
            this.HasKey(t => t.Id);

            // Properties
             
                            this.Property(t => t.UserId);
                         
                            this.Property(t => t.RoleId);
                         
                            this.Property(t => t.CreateId);
                         
                            this.Property(t => t.CreateBy).HasMaxLength(100);;
                         
                            this.Property(t => t.CreateTime);
                         
                            this.Property(t => t.ModifyId);
                         
                            this.Property(t => t.ModifyBy).HasMaxLength(100);;
                         
                            this.Property(t => t.ModifyTime);
                         
                            this.Property(t => t.IsDeleted);
                                    

            // Table & Column Mappings
            this.ToTable("Common_Authen_UserRole");
            this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
             
                this.Property(t => t.UserId).HasColumnName("UserId");
             
                this.Property(t => t.RoleId).HasColumnName("RoleId");
             
                this.Property(t => t.CreateId).HasColumnName("CreateId");
             
                this.Property(t => t.CreateBy).HasColumnName("CreateBy");
             
                this.Property(t => t.CreateTime).HasColumnName("CreateTime");
             
                this.Property(t => t.ModifyId).HasColumnName("ModifyId");
             
                this.Property(t => t.ModifyBy).HasColumnName("ModifyBy");
             
                this.Property(t => t.ModifyTime).HasColumnName("ModifyTime");
             
                this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              
            // Relation
              
        }

		
    }
}
