//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
// <copyright file="OperateLogMap.cs">
//		Copyright(c)2013 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：QuickRMS.Domain.Data
//		生成时间：2014-07-02 14:33
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

using Quick.Framework.EFData;
using QuickRMS.Domain.Models.SysConfig;


namespace QuickRMS.Domain.Data.Mapping.SysConfig
{
    /// <summary>
    /// 数据表映射 —— OperateLog
    /// </summary>    
	partial class OperateLogMap
    {
        /// <summary>
		/// 映射配置
		/// </summary>
        partial void OperateLogMapAppend()
        {
			// Primary Key
            this.HasKey(t => t.Id);

            // Properties
             
                            this.Property(t => t.Area).HasMaxLength(100);;
                         
                            this.Property(t => t.Controller).HasMaxLength(100);;
                         
                            this.Property(t => t.Action).HasMaxLength(100);;
                         
                            this.Property(t => t.IPAddress).HasMaxLength(100);;
                         
                            this.Property(t => t.Description).HasMaxLength(100);;
                         
                            this.Property(t => t.LogTime);
                         
                            this.Property(t => t.LoginName).HasMaxLength(100);;
                         
                            this.Property(t => t.UserId);
                         
                            this.Property(t => t.IsDeleted);
                                    

            // Table & Column Mappings
            this.ToTable("Common_SysConfig_OperateLog");
            this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
             
                this.Property(t => t.Area).HasColumnName("Area");
             
                this.Property(t => t.Controller).HasColumnName("Controller");
             
                this.Property(t => t.Action).HasColumnName("Action");
             
                this.Property(t => t.IPAddress).HasColumnName("IPAddress");
             
                this.Property(t => t.Description).HasColumnName("Description");
             
                this.Property(t => t.LogTime).HasColumnName("LogTime");
             
                this.Property(t => t.LoginName).HasColumnName("LoginName");
             
                this.Property(t => t.UserId).HasColumnName("UserId");
             
                this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              
            // Relation
              
        }

		
    }
}
