//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
// <copyright file="Login_UserMap.cs">
//		Copyright(c)2013 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：QuickRMS.Domain.Data
//		生成时间：2014-07-02 14:33
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

using Quick.Framework.EFData;
using QuickRMS.Domain.Models.SSO;


namespace QuickRMS.Domain.Data.Mapping.SSO
{
    /// <summary>
    /// 数据表映射 —— Login_User
    /// </summary>    
	partial class Login_UserMap
    {
        /// <summary>
		/// 映射配置
		/// </summary>
        partial void Login_UserMapAppend()
        {
			// Primary Key
            this.HasKey(t => t.Id);

            // Properties
             
                            this.Property(t => t.LoginName).HasMaxLength(100);;
                         
                            this.Property(t => t.LoginPwd).HasMaxLength(100);;
                         
                            this.Property(t => t.FullName).HasMaxLength(100);;
                         
                            this.Property(t => t.Email).HasMaxLength(100);;
                         
                            this.Property(t => t.Phone).HasMaxLength(100);;
                         
                            this.Property(t => t.Enabled);
                         
                            this.Property(t => t.PwdErrorCount);
                         
                            this.Property(t => t.LoginCount);
                         
                            this.Property(t => t.RegisterTime);
                         
                            this.Property(t => t.LastLoginTime);
                         
                            this.Property(t => t.CreateId);
                         
                            this.Property(t => t.CreateBy).HasMaxLength(100);;
                         
                            this.Property(t => t.CreateTime);
                         
                            this.Property(t => t.ModifyId);
                         
                            this.Property(t => t.ModifyBy).HasMaxLength(100);;
                         
                            this.Property(t => t.ModifyTime);
                         
                            this.Property(t => t.IsDeleted);
                                    

            // Table & Column Mappings
            this.ToTable("Common_SSO_Login_User");
            this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
             
                this.Property(t => t.LoginName).HasColumnName("LoginName");
             
                this.Property(t => t.LoginPwd).HasColumnName("LoginPwd");
             
                this.Property(t => t.FullName).HasColumnName("FullName");
             
                this.Property(t => t.Email).HasColumnName("Email");
             
                this.Property(t => t.Phone).HasColumnName("Phone");
             
                this.Property(t => t.Enabled).HasColumnName("Enabled");
             
                this.Property(t => t.PwdErrorCount).HasColumnName("PwdErrorCount");
             
                this.Property(t => t.LoginCount).HasColumnName("LoginCount");
             
                this.Property(t => t.RegisterTime).HasColumnName("RegisterTime");
             
                this.Property(t => t.LastLoginTime).HasColumnName("LastLoginTime");
             
                this.Property(t => t.CreateId).HasColumnName("CreateId");
             
                this.Property(t => t.CreateBy).HasColumnName("CreateBy");
             
                this.Property(t => t.CreateTime).HasColumnName("CreateTime");
             
                this.Property(t => t.ModifyId).HasColumnName("ModifyId");
             
                this.Property(t => t.ModifyBy).HasColumnName("ModifyBy");
             
                this.Property(t => t.ModifyTime).HasColumnName("ModifyTime");
             
                this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              
            // Relation
              
        }

		
    }
}
